### ISSUE TITLE
[Bug] Is this deprecated?

### ISSUE THREAD

**Issue by michael-kudrik** [Glagan/tachikoma#1]
I'm assuming that this no longer works since it doesn't seem to have been updated anytime recently. I am getting `Error: Cannot load plugin "typescript": Cannot find package 'typescript' imported from /home/user/Downloads/Assorted Scripts/tachikoma/config/node_modules/rollup/dist/shared/loadConfigFile.js.` when attempting to build. 

I know that you've mentioned in some of the previous work that you really don't update these types of code. Is there another program that you use instead of tachikoma?

**Comment by Glagan** [comment]
This error is just bad documentation for the plugins, I see typescript is not in the dependencies and I think I just had it globally installed so it picked that, you can fix it by either adding it in the dependencies ``yarn add -D typescript`` or installing it globally ``npm install -g typescript``.

But you are right, it was working when I stopped working on it and it appears to be broken now since I didn't follow the last few MangDex updates.  
I don't currently plan to fix it, I started the project for myself and I'm currently not using it, I still plan to update it but I have other projects and they have higher priorities.

I'm not using it but an alternative is malsync.
